/* Database schema to keep the structure of entire database. */ CREATE DATABASE vet_clinic;

CREATE TABLE
    animals (
        id INT GENERATED BY DEFAULT AS IDENTITY,
        name TEXT NOT NULL,
        date_of_birth DATE NOT NULL,
        escape_attempts INT NOT NULL,
        neutered BOOLEAN NOT NULL,
        weight_kg NUMERIC(5, 2) NOT NULL
    );

-- QUWERY AND UPDATE ANIMALS TABLE
ALTER TABLE animals
ADD COLUMN species TEXT;

-- QUWERY MULTIPLE TABLES
CREATE TABLE
    owners (
        id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        full_name VARCHAR(250),
        age INT
    );

CREATE TABLE
    species (
        id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name VARCHAR(250)
    );

ALTER TABLE animals ADD PRIMARY KEY (id);

ALTER TABLE animals
DROP COLUMN species;

ALTER TABLE animals
ADD COLUMN species_id INT REFERENCES species (id);

ALTER TABLE animals
ADD COLUMN owner_id INT REFERENCES owners (id);