CREATE TABLE patients(
	id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name VARCHAR(255),
	date_of_birth DATE,
);

CREATE TABLE medical_histories(
	id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	admitted_at TIMESTAMP,
	patient_id INT REFERENCES patients(id),
	status VARCHAR(255)
);



